project:
  type: website

# Website options and formatting
format:
  html:
    theme: 
    - cosmo
    - styles/custom.css # custom formatting for value boxes
    css: styles.css
    toc: true

website: 
  title: "DETECT Follow-up Interview Master Table"
  # Make the description better later.
  description: "Website containing master descriptive tables for the DETECT follow-up interviews."
  repo-url: https://github.com/brad-cannell/detect_fu_interviews_master_table
  repo-actions: [source, edit, issue]
  page-footer: 
    left: |
      DETECT Follow-up Interviews Master Descriptive Tables
  navbar: 
    search: true
    left: 
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Follow-up Instruments"
        menu: 
          - sections/recruitment_scheduling_dashboard.qmd
          - sections/sociodemographic_tables.qmd
          - sections/general_health_tables.qmd
          - sections/clutter_scale_tables.qmd
          - sections/self_report_tables.qmd
          - sections/aps_investigations_tables.qmd
          - sections/observational_measures_tables.qmd
          - sections/lead_panel_assessment_tables.qmd

# Bibliography and citation options
bibliography: references.bib
csl: ama.csl

# Set editor to default to source view instead of visual view
editor: source

# To make sure that R, Python, and Julia code is only executed locally, 
# configure your project to use Quarto’s freeze feature by adding this to your 
# _quarto.yml. (https://quarto.org/docs/publishing/netlify.html)
execute:
  freeze: auto
  

