project:
  type: book
  output-dir: _book

# Book formatting types and options
format:
  html:
    theme: 
      - cosmo
  pdf:
    documentclass: scrreprt

# Bibliography and citation options
bibliography: references.bib
csl: ama.csl

# Set editor to default to source view instead of visual view
editor: source

# To make sure that R, Python, and Julia code is only executed locally, 
# configure your project to use Quarto’s freeze feature by adding this to your 
# _quarto.yml. (https://quarto.org/docs/publishing/netlify.html)
execute:
  freeze: auto

# Book structure and options
book:
  # Basic metadata
  title: "DETECT Follow-up Interviews Master Descriptive Tables"
  date: today # Figure out how to automatically update the date on render.
  repo-url: https://github.com/brad-cannell/detect_fu_interviews_master_table
  repo-actions: [source, edit, issue]
  page-footer: 
    left: |
      DETECT Follow-up Interviews Master Descriptive Tables
  
  # Book options
  search: true
  downloads: [pdf, docx] # https://quarto.org/docs/books/book-output.html#sidebar-tools
  page-navigation: true # Haven't played with this much yet. https://quarto.org/docs/books/book-structure.html#page-navigation

  # Chapter sturcture
  # https://quarto.org/docs/books/book-structure.html
  chapters:
    # Index is the landing page for the HTML version of the book.
    - index.qmd
    - about.qmd
    
    # My chapters
    # Parts can be qmd files (if you want explanitory text) or characater strings
    # If you only want a part title.
    # This method does not look good in pdf format.
    - part: "Recruitment and Scheduling"
      # Make sure to type "chapters" again under each part.
      chapters: 
      - sections/recruitment_scheduling.qmd
      
    - part: "Sociodemographic Information"
        
    - part: "General Health"
        
    - part: "Home Inspection"
    
    - part: "EM Self-Report"
    
    - part: "APS Investigations"
    
    - part: "Interviewer Observations"
    
    - part: "LEAD Panel Assessment"

